### ISSUE TITLE
[BUG] - Bug in adding a donation

### ISSUE THREAD

**Issue by rsc1102** [gcivil-nyu-org/wed-fall24-team5#300]
**Description**
When creating a new donation, if the pickup date is set for tomorrow, a message appears "Please enter a valid date within 1 week from today."

**Steps to Reproduce**
1. Log in.
2. Go to Organizations.
3. Click to view Uncle Steve’s Marketplace.
4. Click on add donation.
5. Set the pickup date to the next day. 
6. The modal will show "Please enter a valid date within 1 week from today."

**Expected Behavior**
The expected behavior is that there should not be any error for the next day's date as it falls within 1 week from today.

**Screenshots or Code Snippets (required)**
Image captured on 13th Nov 2024, 8 pm EST.
![image](https://github.com/user-attachments/assets/521e9f4c-9149-4dfb-9f0b-142ee3c5c595)

**Additional Context (optional)**
Despite showing the warning, the user is able to add the donation.

**Comment by arsalananwar11** [comment]
Hey @rsc1102, I don't think it is a bug but more of an enhancement. It is just displaying the message on the UI stating that the date should be within a week from today which is what that got checked in the backend. Since the date you entered passed the verification, you were able to add the donation. We will consider removing the message if it is causing confusion.
