### ISSUE TITLE
[SUGGESTION] - Display only the donations which match the dietary restrictions specified in the user profile

### ISSUE THREAD

**Issue by thejaswinidm** [gcivil-nyu-org/wed-fall24-team5#332]
**Summary**
Currently user can view all the food types despite of their dietary restrictions listed in the profile

**Problem Statement**
If a user selects their dietary preference as Vegan, the dashboard displays all the food items (steak etc) available without considering their dietary restrictions.

**Proposed Solution**
Consider filtering the food items displayed based on their dietary restrictions.
Ex: If I am vegan I should only see vegan options displayed on the dashboard.

**Additional Feature**
It would be helpful to include details about the donated food's contents.
 For instance, if I have a severe walnut allergy and there's a cake among the donations, it would be crucial to know the ingredients beforehand to ensure it doesn’t contain walnuts.

**Comment by maxgrove42** [comment]
Hey @thejaswinidm - thanks for testing! This is currently expected behavior - the dietary preferences are a UI only feature. 

The expected flow is that the organization sees the dietary preferences and should message the recipient to explain that their food item is not compatible with the dietary preferences selected. Theoretically, a user might have their own dietary preferences, but could be picking up for a friend in need, or a group.

<img width="1413" alt="Screenshot 2024-11-16 at 12 58 33 PM" src="https://github.com/user-attachments/assets/bfab9d8a-288d-4836-af3d-e4a2840d6153">

We'll take this suggestion and prioritize it for a future sprint! I love your idea that the organization could include donated food's content.

**Comment by maxgrove42** [comment]
Potentially something for the last sprint: add in the ability to add common dietary flags / allergies matching what we have in user preferences. Then we can add into the search bar something like "only show donations matching my dietary preferences"

**Comment by arsalananwar11** [comment]
Wont be working on this as this is a part of optional enhancement
